[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
test_lib = []

[dependencies]
pico-args = "0.5.0"
